CREATE TABLE IF NOT EXISTS image (
  id int(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  uploaded timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  name varchar(255) NOT NULL,
  note text NULL
);
